trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SC'
    organization: 'bc-sonarcloud-training'
    scannerMode: 'MSBuild'
    projectKey: 'dc-sample'
    projectName: 'DotNet Core Sample'

# Dotnet build task
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'


- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'